steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/site3score/default:v3',
        '--build-arg',
        'API_KEY=$_API_KEY',
        '--build-arg',
        'SERVICE_DOMAIN=$_SERVICE_DOMAIN',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/site3score/default:v3']
